tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "phrase/brewed"
tap "wtfutil/wtfutil"
tap "adoptopenjdk/openjdk"

# utility/essential
brew "ffmpeg"
brew "fzf"
brew "gifsicle"
brew "gpg"
brew "hub"
brew "htop"
brew "mas"
brew "mosh"
brew "pinentry-mac"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "wtfutil"
brew "zsh"

# development dependencies
cask "adoptopenjdk8"
brew "nvm"
brew "postgresql", restart_service: true
brew "yarn"
brew "awscli"
brew "ant"
brew "maven"
brew "gradle"

# games and fun stuff
brew "archey"
brew "bastet"
brew "cheat"
brew "cmatrix"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "greed"
brew "moon-buggy"
brew "nethack"
brew "ninvaders"
brew "nsnake"
brew "sl"
brew "wakeonlan"
brew "youtube-dl"

# native and gui apps
cask "1password"
cask "aerial"
cask "android-sdk"
cask "android-ndk"
cask "android-studio"
cask "alfred"
cask "atom"
cask "brave-browser"
cask "cathode"
cask "diskwave"
cask "gimp"
cask "github"
cask "iterm2"
cask "minecraft"
cask "mixxx"
cask "nordvpn"
cask "omnidisksweeper"
cask "openemu"
cask "opera"
cask "pock"
cask "react-native-debugger"
cask "sequel-pro"
cask "simple-comic"
cask "slack"
cask "spectacle"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "workflowy"

# mac app store
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.apple.dt.Xcode", id: 497799835
