tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "phrase/brewed"
tap "adoptopenjdk/openjdk"

repo = 'yujitach/MenuMeters'
tap repo, "https://github.com/#{repo}.git"

# utility/essential
cask "applite"
brew "ffmpeg"
brew "gifsicle"
brew "gpg"
brew "htop"
brew "mas"
brew "ssh-copy-id"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "yt-dlp"

# development dependencies
cask "adoptopenjdk8"
cask "adoptopenjdk11"
brew "nvm"
brew "postgresql", restart_service: true
brew "awscli"
brew "ant"
brew "maven"
brew "gradle"
brew "nginx"
brew "watchman"

# games and fun stuff
brew "archey"
brew "bastet"
brew "cheat"
brew "cmatrix"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "greed"
brew "moon-buggy"
brew "nethack"
brew "ninvaders"
brew "nsnake"
brew "sl"

# native and gui apps
cask "1password"
cask "aerial"
cask "android-sdk"
cask "android-ndk"
cask "android-studio"
cask "alfred"
cask "brave-browser"
cask "balenaetcher"
cask "discord"
cask "deluge"
cask "diskwave"
cask "epic-games"
cask "firefox"
cask "gimp"
cask "iterm2"
cask "lm-studio"
cask "menumeters"
cask "minecraft"
cask "mixxx"
cask "nordvpn"
brew "ollama"
cask "omnidisksweeper"
cask "openemu"
cask "opera"
cask "paintbrush"
cask "plex"
cask "postman"
cask "react-native-debugger"
cask "sequel-pro"
cask "simple-comic"
cask "slack"
cask "steam"
cask "spectacle"
cask "spotify"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "workflowy"
cask "whisky"

# mac app store
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.apple.dt.Xcode", id: 497799835
